---
apiVersion: v1
kind: Service
metadata:
  name: juno-genesis
  labels:
    app.kubernetes.io/name: juno-genesis
spec:
  clusterIP: None
  ports:
    - name: p2p
      port: 26656
      protocol: TCP
      targetPort: 26656
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: 26657
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: rest
      port: 1317
      protocol: TCP
      targetPort: 1317
  selector:
    app.kubernetes.io/name: juno-genesis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: juno-genesis
spec:
  serviceName: juno-genesis
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: juno
      app.kubernetes.io/name: juno-genesis
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: juno
        app.kubernetes.io/type: juno-validator
        app.kubernetes.io/name: juno-genesis
        app.kubernetes.io/version: '0.1'
    spec:
      initContainers:
        - name: init-genesis
          image: persistenceone/juno:latest
          imagePullPolicy: Always
          env:
            - name: COINS
              value: "100000000000000000ujuno"
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: juno
            - name: HOME_DIR
              value: /juno
          command:
            - bash
            - "-c"
            - |
              VAL_INDEX=${HOSTNAME##*-}
              echo "Validator Index: $VAL_INDEX"

              junod init juno --chain-id $CHAIN_ID --home $HOME_DIR
              jq -r ".genesis[0].mnemonic" /configs/validators.json | junod keys add $(jq -r ".genesis[0].name" /configs/validators.json) --recover --keyring-backend='test' --home $HOME_DIR

              # Provide genesis validator self deligations
              junod add-genesis-account $(jq -r .genesis[$i].address /configs/validators.json) $COINS --keyring-backend='test' --home $HOME_DIR

              # Give Validator addresses initial coins
              for ((i=0; i<$(jq -r '.validators | length' /configs/validators.json); i++))
              do
                jq -r ".validators[$i].mnemonic" /configs/validators.json | junod keys add $(jq -r ".validators[$i].name" /configs/validators.json) --recover --keyring-backend='test' --home $HOME_DIR
                junod add-genesis-account $(jq -r .validators[$i].address /configs/validators.json) $COINS --keyring-backend='test' --home $HOME_DIR
              done
              # Give test addresses initial coins
              for ((i=0; i<$(jq -r '.keys | length' /configs/keys.json); i++))
              do
                jq -r ".keys[$i].mnemonic" /configs/keys.json | junod keys add $(jq -r ".keys[$i].name" /configs/keys.json) --recover --keyring-backend='test' --home $HOME_DIR
                junod add-genesis-account $(jq -r .keys[$i].address /configs/keys.json) $COINS --keyring-backend='test' --home $HOME_DIR
              done

              junod gentx $(jq -r ".genesis[0].name" /configs/validators.json) 5000000000ujuno --keyring-backend="test" --chain-id $CHAIN_ID --home $HOME_DIR
              echo "Output of gentx"
              cat $HOME_DIR/config/gentx/*.json | jq

              echo "Running collect-gentxs"
              junod collect-gentxs --home $HOME_DIR

              sed -i 's#"tcp://127.0.0.1:26657"#"tcp://0.0.0.0:26657"#g' $HOME_DIR/config/config.toml
              sed -i 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $HOME_DIR/config/config.toml
              sed -i 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $HOME_DIR/config/config.toml
              sed -i 's/index_all_keys = false/index_all_keys = true/g' $HOME_DIR/config/config.toml
              sed -i 's/unsafe = false/unsafe = true/g' $HOME_DIR/config/config.toml
              sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "0.00ujuno"/g' $HOME_DIR/config/config.toml
              sed -i 's/cors_allowed_origins = []/cors_allowed_origins = ["*"]/g' $HOME_DIR/config/config.toml

              sed -i 's/enable = false/enable = true/g' $HOME_DIR/config/app.toml
              sed -i 's/swagger = false/swagger = true/g' $HOME_DIR/config/app.toml
              sed -i 's/enabled-unsafe-cors = false/enabled-unsafe-cors = true/g' $HOME_DIR/config/app.toml

              jq '.consensus_params.block.max_bytes |= "42020096"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.gov.voting_params.voting_period |= "30s"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.gov.tally_params.quorum |= "0.0"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.gov.deposit_params.min_deposit[0].amount |= "10"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json

              jq '.app_state.crisis.constant_fee.denom |= "ujuno"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.gov.deposit_params.min_deposit[0].denom |= "ujuno"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.liquidity.params.pool_creation_fee[0].denom |= "ujuno"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.mint.params.mint_denom |= "ujuno"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json
              jq '.app_state.staking.params.bond_denom |= "ujuno"' $HOME_DIR/config/genesis.json | tee $HOME_DIR/config/genesis.new.json
              mv $HOME_DIR/config/genesis.new.json $HOME_DIR/config/genesis.json

              sed -i 's/stake/ujuno/g' $HOME_DIR/config/genesis.json

              echo "TRYING TO PRINT GENESIS JSON"
              cat $HOME_DIR/config/genesis.json | jq

              junod tendermint show-node-id --home $HOME_DIR > $HOME_DIR/genesis-node-id.txt
          resources:
            limits:
              cpu: "0.2"
              memory: "200M"
            requests:
              cpu: "0.1"
              memory: "100M"
          volumeMounts:
            - mountPath: /juno
              name: juno
            - mountPath: /configs
              name: addresses
      containers:
        - name: validator
          image: persistenceone/juno:latest
          imagePullPolicy: Always
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: juno
            - name: HOME_DIR
              value: /juno
          command:
            - bash
            - "-c"
            - |
              junod start --home $HOME_DIR
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "0.5"
              memory: "500M"
          volumeMounts:
            - mountPath: /juno
              name: juno
            - mountPath: /configs
              name: addresses
        - name: exposer-app
          image: persistenceone/exposer:latest
          imagePullPolicy: Always
          env:
            - name: GENESIS_FILE
              value: /juno/config/genesis.json
            - name: PORT
              value: "8081"
          command: [ "exposer" ]
          resources:
            limits:
              cpu: "0.1"
              memory: "100M"
            requests:
              cpu: "0.1"
              memory: "100M"
          volumeMounts:
            - mountPath: /juno
              name: juno
      volumes:
        - name: juno
          emptyDir: { }
        - name: addresses
          configMap:
            name: test-addresses-juno
---
