name: 'Test'
on:
  push:
    branches:
      - anmol/k8s

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-shuttle

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup shuttle helm repo
        run: |
          helm version
          helm repo add shuttle https://anmol1696.github.io/shuttle
          helm repo update
          helm search repo shuttle/devnet

      - name: Create values.yaml
        run: |
          cat << EOF > custom-values.yaml
          chains:
          - name: osmosis-1
            type: osmosis
            numValidators: 1
            ports:
              rest: 1313
              rpc: 26653
            resources:
              limits:
                cpu: "0.5"
                memory: "1G"
              requests:
                cpu: "0.2"
                memory: "500M"
          - name: wasmd
            type: wasmd
            numValidators: 1
            ports:
              rpc: 26659
              rest: 1319
            resources:
              limits:
                cpu: "0.5"
                memory: "1G"
              requests:
                cpu: "0.2"
                memory: "500M"
          EOF
          pwd
          cat custom-values.yaml

      - name: Check resources
        run: |
          kubectl get nodes -oyaml
          free -mh
          sar -u 2 10

      - name: Helm install
        run: |
          helm install -f custom-values.yaml testdevnet shuttle/devnet --wait --debug

      - name: Get pods
        run: |
          kubectl get pods

      - name: Port forward local ports
        run: |
          kubectl port-forward pods/osmosis-1-genesis-0 26653:26657 &
          kubectl port-forward pods/wasmd-genesis-0 26659:26657 &

      - name: Run tests locally
        run: |
          cd tests/
          npm run test

      - name: Cleanup shuttle cluster
        if: always()
        run: |
          helm delete testdevnet
