name: 'Test'
on:
  push:
    branches:
      - anmol/k8s

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-shuttle

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Setup shuttle helm repo
        run: -|
          helm repo add shuttle https://anmol1696.github.io/shuttle/
          helm repo update
          helm search repo shuttle/devnet

      - name: Create values.yaml
        run: -|
          cat << EOF > custom-values.yaml
          chains:
            - name: osmosis-1
              type: osmosis
              numValidators: 1
              ports:
                rest: 1313
                rpc: 26653
            - name: wasmd
              type: wasmd
              numValidators: 1
              ports:
                rpc: 26659
                rest: 1319
          EOF
          pwd
          cat custom-values.yaml

      - name: Helm install
        run: -|
          helm install -f custom-values.yaml testdevnet shuttle/devnet

      - name: Get pods
        run: -|
          kubectl get pods

      - name: Port forward local ports
        run: -|
          kubectl port-forward pods/osmosis-1-genesis-0 26653:26657 &
          kubectl port-forward pods/wasmd-genesis-0 26659:26657 &

      - name: Get pods again
        run: -|
          kubectl get pods

      - name: Run tests locally
        run: -|
          sleep 60
          cd tests/
          npm run test

      - name: Cleanup shuttle cluster
        if: always()
        run: -|
          helm delete testdevnet
