name: 'Test'
on:
  push:
    branches:
      - anmol/k8s

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-shuttle

      - name: Create shuttle cluster
        uses: deliverybot/helm@v1
        with:
          release: local-shuttle
          token: ${{ github.token }}
          version: ${{ github.sha }}
          namespace: default
          repo: https://anmol1696.github.io/shuttle
          chart: shuttle/devnet
          chart-version: 0.1.3
          values: |
            chains:
              - name: osmosis-1
                type: osmosis
                numValidators: 1
                ports:
                  rest: 1313
                  rpc: 26653
              - name: wasmd
                type: wasmd
                numValidators: 1
                ports:
                  rpc: 26659
                  rest: 1319

      - name: Get pods
        run: -|
          kubectl get pods

      - name: Port forward local ports
        run: -|
          kubectl port-forward pods/osmosis-1-genesis-0 26653:26657 &
          kubectl port-forward pods/wasmd-genesis-0 26659:26657 &

      - name: Get pods again
        run: -|
          kubectl get pods

      - name: Run tests locally
        run: -|
          sleep 60
          cd tests/
          npm run test

      - name: Cleanup shuttle cluster
        if: always()
        uses: deliverybot/helm@v1
        with:
          task: remove
          release: local-shuttle
          token: ${{ github.token }}
          version: ${{ github.sha }}
          namespace: default
          chart: shuttle/devnet
          chart-version: 0.1.3
          repo: https://anmol1696.github.io/shuttle
